/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import static Interfaz.MenuPrincipal.bd;
import java.util.List;

/**
 *
 * @author krisc
 */
public class Podio extends javax.swing.JFrame {
    
    
    
    List<Objetos.Marca> podio3x3Facil = bd.sacarMejoresMarcas(3,1);
    List<Objetos.Marca> podio4x4Facil = bd.sacarMejoresMarcas(4,1);
    List<Objetos.Marca> podio5x5Facil = bd.sacarMejoresMarcas(5,1);
    List<Objetos.Marca> podio6x6Facil = bd.sacarMejoresMarcas(6,1);
    List<Objetos.Marca> podio7x7Facil = bd.sacarMejoresMarcas(7,1);
    List<Objetos.Marca> podio8x8Facil = bd.sacarMejoresMarcas(8,1);
    List<Objetos.Marca> podio9x9Facil = bd.sacarMejoresMarcas(9,1);


    List<Objetos.Marca> podio3x3Medio = bd.sacarMejoresMarcas(3,2);
    List<Objetos.Marca> podio4x4Medio = bd.sacarMejoresMarcas(4,2);
    List<Objetos.Marca> podio5x5Medio = bd.sacarMejoresMarcas(5,2);
    List<Objetos.Marca> podio6x6Medio = bd.sacarMejoresMarcas(6,2);
    List<Objetos.Marca> podio7x7Medio = bd.sacarMejoresMarcas(7,2);
    List<Objetos.Marca> podio8x8Medio = bd.sacarMejoresMarcas(8,2);
    List<Objetos.Marca> podio9x9Medio = bd.sacarMejoresMarcas(9,2);
    
    List<Objetos.Marca> podio3x3Dificil = bd.sacarMejoresMarcas(3,3);
    List<Objetos.Marca> podio4x4Dificil = bd.sacarMejoresMarcas(4,3);
    List<Objetos.Marca> podio5x5Dificil = bd.sacarMejoresMarcas(5,3);
    List<Objetos.Marca> podio6x6Dificil = bd.sacarMejoresMarcas(6,3);
    List<Objetos.Marca> podio7x7Dificil = bd.sacarMejoresMarcas(7,3);
    List<Objetos.Marca> podio8x8Dificil = bd.sacarMejoresMarcas(8,3);
    List<Objetos.Marca> podio9x9Dificil = bd.sacarMejoresMarcas(9,3);
    
    /*
    podio3x3Facil[0].nombre
    
    */
    
    
    /**
     * Creates new form Podio
     */
    public Podio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 239, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PODIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 33, -1, -1));

        jPanel2.setBackground(new java.awt.Color(65, 91, 63));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Podio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
